server:
  tomcat:
    max-threads: 3000
    min-spare-threads: 10
  port: 3020
eureka:
  client:
    service-url:
        defaultZone: http://10.111.0.151:8761/eureka/,http://10.111.0.152:8761/eureka/
    should-unregister-on-shutdown: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
spring:
  application:
    name: flowengine-api
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rds07rzqa6g5f95hoooi601.mysql.rds.aliyuncs.com:3388/db_flow_engine?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: user_flow_engine
    password: xiBuCIPhXc1
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      validation-query: select 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  transaction:
    rollback-on-commit-failure: true
  redis:
    host: bookeeping.redis.rds.aliyuncs.com
    port: 6379
    password: GLpIEnf#*WIfpM#P
    #       password: dh35hebsd87ed9df9d0kemd9
    lettuce:
      pool:
        min-idle: 4
        max-active: 8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 5Mb
      max-request-size: 10Mb
mybatis:
  mapperLocations: classpath:mapper/**/*.xml

rocketmq:
  producer:
    access-key: i3xR4RSOyYNBPZSb
    secret-key: kU1Wd69jUH56ACMk0uqJi2lxA34R3g
    ons-address: http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet
    group-id: GID_flow_engine_server
    topic: flow-engine-state-topic
